name: Package-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # - name: ECS
    #   run: vendor/bin/ecs check

    # - name: Psalm
    #   run: vendor/bin/psalm --show-info=false --no-cache

    # - name: Phpstan
    #   run: ./vendor/bin/phpstan analyse
